import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

const Home: NextPage = () => {
  const [text, setText] = useState("");
  const [result, setResult] = useState("");
  const [lang, setLang] = useState("DescriptionEn");
  const [isLoading, setIsLoading] = useState(false);

  const handleChange = (event: any) => {
    setLang(event.target.value);
  };

  const translateHandler = async () => {
    setIsLoading(true);
    try {
      const response = await fetch(
        `http://3.239.239.251/translate?text=${text}&target_lang=${lang}`
      );
      const result = await response.text();
      setIsLoading(false);
      let jsonObj = JSON.parse(result);
      setResult(jsonObj?.translation);
    } catch (error) {
      setIsLoading(false);
      alert("error");
      console.log("Error:", error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>SS-AI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isLoading ? (
          <div className="loader-cont">
            <div className="loadingio-spinner-ripple-cmyt7s2fej9">
              <div className="ldio-8g16pyg0jxd">
                <div></div>
                <div></div>
              </div>
            </div>
          </div>
        ) : (
          <></>
        )}
        <h1 className={"title"}>
          Welcome to{" "}
          <a className={"title-span"} href="https://nextjs.org">
            SS-AI!
          </a>
        </h1>

        <div className={"form"}>
          <textarea
            value={text}
            onChange={(e) => {
              setText(e.target?.value);
            }}
            className="my-textarea"
          />
          <select className="my-selector" value={lang} onChange={handleChange}>
            <option value="DescriptionEn">English</option>
            <option value="DescriptionRu">Русский</option>
            <option value="DescriptionGe">ქართული</option>
          </select>
          <button
            className="my-button"
            type="button"
            onClick={() => translateHandler()}
          >
            Translate
          </button>
        </div>
        <div className="result">
          <p className="result-text">
            {result?.length ? result : "Results will be here...."}
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}>Lemondo</span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
